#!/usr/bin/env bash
#It displays the contents of the current directory in list format.
#It only displays the part of the name after the first dash. 

list=$(ls)
	for i in $list; do
	echo "$i" | cut -d '-' -f2
	done
